theme = "custom-simple"

[keys.normal]
"C-s" = ":write"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"x" = ["goto_line_start", "select_mode", "goto_line_end_newline"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.insert]
"C-s" = ":write"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
"C-s" = ":write"

[keys.normal.space]
"space" = "hover"
"q" = ":q"
"f" = ":format"
"F" = "no_op"
"e" = "file_picker"
"E" = "file_picker_in_current_directory"
"k" = "file_explorer"
"K" = "file_explorer_in_current_buffer_directory"

[keys.select.space]
"space" = "hover"
"q" = ":q"
"f" = ":format"
"F" = "no_op"
"e" = "file_picker"
"E" = "file_picker_in_current_directory"
"k" = "file_explorer"
"K" = "file_explorer_in_current_buffer_directory"

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator", "read-only-indicator", "spinner"]
right = ["diagnostics", "selections", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.lsp]
display-messages = true

[editor]
color-modes = true
end-of-line-diagnostics = "hint"
gutters = ["line-numbers", "diagnostics"]
cursorline = true
 
[editor.inline-diagnostics]
cursor-line = "hint"
max-diagnostics = 3

