[mgr]
syntect_theme = "~/.config/yazi/highlight.tmTheme"

[mode]
normal_main = { fg = "cyan", bg = "black" }
select_main = { fg = "magenta", bg = "black" }

[status]
overall = { bg = "#262626" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[tabs]
inactive = { bg = "#262626", fg = "blue" }
sep_outer = { open = "█", close = "█" }
active = { fg = "#262626", bg = "blue" }
sep_inner = { open = "", close = "" }
